### ISSUE TITLE
Program not Creating all .asc files

### ISSUE THREAD

**Issue by bmartin598** [furrysalamander/mini-map-maker#4]
When I run the program it always fails by resulting in being unable to find a .asc file. I have tried with several different data sets from the USGS map. It does this with the .py and .exe versions

Suggestions?

```
Generating .asc files...

ASC\USGS_LPC_CO_Central_Western_2016_LD28711641_LAS_2018.asc
   Cannot open input surface model: DTM\USGS_LPC_CO_Central_Western_2016_LD28711641_LAS_2018.dtm
Traceback (most recent call last):
  File "D:\Lidar\convert.py", line 210, in <module>
    main()
  File "D:\Lidar\convert.py", line 192, in main
    asc_parse.gen_stls_from_ascs(
  File "D:\Lidar\asc_parse.py", line 24, in gen_stls_from_ascs
    list_of_depth_maps = [load_asc(x) for x in list_of_asc]
  File "D:\Lidar\asc_parse.py", line 24, in <listcomp>
    list_of_depth_maps = [load_asc(x) for x in list_of_asc]
  File "D:\Lidar\asc_parse.py", line 9, in load_asc
    data = np.loadtxt(file_name, skiprows=7)
  File "C:\Users\bmart\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\npyio.py", line 961, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\Users\bmart\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\Users\bmart\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: ASC\USGS_LPC_CO_Central_Western_2016_LD28711641_LAS_2018.asc not found.
```

**Comment by furrysalamander** [comment]
I wonder if this is related to the problems it was having finding your executables earlier.

**Comment by bmartin598** [comment]
> I wonder if this is related to the problems it was having finding your executables earlier.

Hmm thats a thought. I'll see if its saving it to a folder not in my path.

**Comment by bmartin598** [comment]
> > I wonder if this is related to the problems it was having finding your executables earlier.
> 
> Hmm thats a thought. I'll see if its saving it to a folder not in my path.

Nope. Manually added all the folders that are getting created by the program to my environments path and still can't find the .asc file.

Is there a way for me to stop the program after its generated those files and actually look at them? That way I can try and see if it is generating them to begin with? All of the files except the .zip and .las are not in the subfolders after the script fails.

**Comment by furrysalamander** [comment]
So it looks like the error at the bottom is actually cascading from the one at the top.  We'll have to start by figuring out why the .dtm files aren't getting generated properly.
`Cannot open input surface model: DTM\USGS_LPC_CO_Central_Western_2016_LD28711641_LAS_2018.dtm`

**Comment by bmartin598** [comment]
How can I help figure this out?

**Comment by bmartin598** [comment]
I have troubleshooted this over the last couple days. It looks like if I run the script without any arguments except the input file argument it works. If i try to run it with the -m it doesn't work. After running it successfully I can sometimes get -m to work but not always.

**Comment by furrysalamander** [comment]
@bmartin598 thank you for your feedback.  I am sorry I haven't had time to look at your problem in more depth yet.  I am a bit behind in some of my classes, but hoping to be caught up soon, and then I can put some time into working on another release with fixes for all of these bugs.
